title: Resources for learning more about compilers
description: Here are a few more books and videos that explain more about compilers. This is a companion to our presentation on how compilers translate code into machine code.
